name: conda_11
channels:
  - pytorch
  - nvidia
  - conda-forge
  - metric-learning
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pytorch-lightning
  - pytorch-metric-learning
  - scikit-learn
  - pyproj
  - matplotlib
  - pandas
  - opencv
  - rasterio
  - utm
  - faiss
  - prettytable
  - tqdm
  - pip
  - b2sdk